version: '2.1'

services:
  database:
    image: mongo
    ports:
      - 27017:27017
  apollo-server:
    image: apollo-server
    build: .
    ports:
      - 6000:6000
    volumes:
      - .:/usr/src/app